# Generated by Django 6.0.3 on 2026-04-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='british_year',
            new_name='birth_year',
        ),
        migrations.AddField(
            model_name='director',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
